[package]
name = "obsidian-links"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
comrak = { workspace = true }
log = { workspace = true }
obsidian-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }
